// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OsuHelper.Models;

#nullable disable

namespace OsuHelper.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220529182602_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("OsuHelper.Models.OsuReplay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BeatmapMD5Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Combo")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Count100")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Count300")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Count50")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("CountGeki")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("CountKatu")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("CountMiss")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filename")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mods")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OnlineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OsuVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PerfectCombo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplayLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplayMD5Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplayScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReplayTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ruleset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Replays");
                });
#pragma warning restore 612, 618
        }
    }
}
